#if !defined(SHADER_CONSTANTS_H)
#define SHADER_CONSTANTS_H

#define MAX_LIGHTS 4

#define SHADOWMAP_SIZE 1024
#define MAX_SHADOWMAPS 2

// Registers
#define CB_REGISTER_PER_FRAME b0
#define CB_REGISTER_PER_OBJECT b1
#define CB_REGISTER_LIGHTS b2
#define CB_REGISTER_MATERIAL b3

#define TEX_REGISTER_SHADOWMAP0 t0
#define TEX_REGISTER_SHADOWMAP1 t1
#define TEX_REGISTER_USER0 t2
#define TEX_REGISTER_USER1 t3

#define SAM_REGISTER_SHADOWMAP0 s0
#define SAM_REGISTER_SHADOWMAP1 s1
#define SAM_REGISTER_USER0 s2
#define SAM_REGISTER_USER1 s3

#endif